name: PR Target Check
on:
  pull_request:
    types: [opened, edited]
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is targeting the 'develop' branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" != "develop" ]; then
            echo "::error file=${{ github.event.pull_request.url }}::PR is not targeting 'develop'. Please change the target branch to 'develop'."
            exit 1
          else
            echo "PR is targeting the 'develop' branch. Everything is okay."
          fi
